// anban-board-angular/src/app/kanbanBoard/kanbanBoard.component.ts
import {Component, OnInit} from '@angular/core';

@Component({
  selector: 'kanban-board',
  templateUrl: './kanbanBoard.component.html',
  styleUrls: ['./kanbanBoard.component.scss']
})
export class KanbanBoard implements OnInit {
  tasks: Task[];
  stagesNames: string[];
  public newTask: string;
  public taskLength: number;
  stagesTasks: any[]; //Only used for rendering purpose

  ngOnInit() {
    // Each task is uniquely identified by its name.
    // Therefore, when you perform any operation on tasks, make sure you pick tasks by names (primary key) instead of any kind of index or any other attribute.
    this.tasks = [
      { name: '0', stage: 0 },
      { name: '1', stage: 0 },
    ];
    this.stagesNames = ['Backlog', 'To Do', 'Ongoing', 'Done'];
    this.configureTasksForRendering();
  }
  createTask(){
    if(!this.newTask){
      return ;
    }
    this.tasks.push({
      name: this.newTask, stage: 0
    });
    this.newTask = '';
    this.configureTasksForRendering();
  }

  // this function has to be called whenever tasks array is changed to construct stagesTasks for rendering purpose
  configureTasksForRendering = () => {
    this.stagesTasks = [];
    for (let i = 0; i < this.stagesNames.length; ++i) {
      this.stagesTasks.push([]);
    }
    for (let task of this.tasks) {
      const stageId = task.stage;
      this.stagesTasks[stageId].push(task);
    }
    this.taskLength = this.tasks.length;
  }
  forwardMove(task){
    this.tasks = this.tasks.map(i => {
      if(i.name === task.name){
        i.stage = i.stage + 1;
      }
      return i;
    });
    this.configureTasksForRendering();

  }
  backMove(task){
    this.tasks = this.tasks.map(i => {
      if(i.name === task.name){
        i.stage = i.stage - 1;
      }
      return i;
    });
    this.configureTasksForRendering();

  }
  delete(task){
    this.tasks = this.tasks.filter(i => {
      if(i.name !== task.name){
        return i
      }
    });
    this.configureTasksForRendering();
  }

  generateTestId = (name) => {
    return name.split(' ').join('-');
  }
}

interface Task {
  name: string;
  stage: number;
}

// kanban-board-react/src/components/kanban-board/index.js
import React, { Component } from "react";
import "./index.css";

export default class KanbanBoard extends Component {
  constructor() {
    super();
    // Each task is uniquely identified by its name.
    // Therefore, when you perform any operation on tasks, make sure you pick tasks by names (primary key) instead of any kind of index or any other attribute.
    this.state = {
      newTask: "",
      tasks: [
        { name: "1", stage: 0 },
        { name: "2", stage: 0 },
      ],
    };
    this.stagesNames = ["Backlog", "To Do", "Ongoing", "Done"];
  }
  handleChange(e) {
    const { value} = e.target;
    this.setState((currentState) => {
      return {
        ...currentState,
        newTask: value,
      };
    });
    e.stopPropagation();
  }
  handleSubmit() {
    const { tasks, newTask } = this.state;
    if (!this.state.newTask) {
      return;
    } else {
      const tasksArray = [...tasks];
      tasksArray.push({ name: newTask, stage: 0 });
      this.setState({ tasks: tasksArray, newTask: ''});
    }
  }

  handleForward(task){
    const {tasks} = this.state;
    const copyTasks = tasks.map(i => {
      if(i.name === task.name){
        i.stage = i.stage + 1;
      }
      return i;
    });
    this.setState({tasks: copyTasks});

  }
  handleBack(task){
    const {tasks} = this.state;
    const copyTasks = tasks.map(i => {
      if(i.name === task.name){
        i.stage = i.stage - 1;
      }
      return i;
    });
    this.setState({tasks: copyTasks});
  }
  delete(task){
    const {tasks} = this.state;
    const copyTasks = tasks.filter(i => {
      if(i.name !== task.name){
        return i;
      }
    });
    this.setState({tasks: copyTasks});
  }

  render() {
    const { tasks, newTask } = this.state;

    let stagesTasks = [];
    for (let i = 0; i < this.stagesNames.length; ++i) {
      stagesTasks.push([]);
    }
    for (let task of tasks) {
      const stageId = task.stage;
      stagesTasks[stageId].push(task);
    }

    return (
      <div className="mt-20 layout-column justify-content-center align-items-center">
        <section className="mt-50 layout-row align-items-center justify-content-center">
          <input
            onChange={(e) => this.handleChange(e)}
            value={newTask}
            id="create-task-input"
            type="text"
            className="large"
            placeholder="New task name"
            data-testid="create-task-input"
          />
          <button
            onClick={(e) => this.handleSubmit()}
            type="submit"
            className="ml-30"
            data-testid="create-task-button"
          >
            Create task
          </button>
        </section>

        <div className="mt-50 layout-row">
          {stagesTasks.map((tasks, i) => {
            return (
              <div className="card outlined ml-20 mt-0" key={`${i}`}>
                <div className="card-text">
                  <h4>{this.stagesNames[i]}</h4>
                  <ul className="styled mt-50" data-testid={`stage-${i}`}>
                    {tasks.map((task, index) => {
                      return (
                        <li className="slide-up-fade-in" key={`${i}${index}`}>
                          <div className="li-content layout-row justify-content-between align-items-center">
                            <span
                              data-testid={`${task.name
                                .split(" ")
                                .join("-")}-name`}
                            >
                              {task.name}
                            </span>
                            <div className="icons">
                              <button
                                className="icon-only x-small mx-2"
                                disabled={task.stage === 0}
                                onClick={() => this.handleBack(task)}
                                data-testid={`${task.name
                                  .split(" ")
                                  .join("-")}-back`}
                              >
                                <i className="material-icons">arrow_back</i>
                              </button>
                              <button
                                className="icon-only x-small mx-2"
                                disabled={task.stage === 3}
                                onClick={() => this.handleForward(task)}
                                data-testid={`${task.name
                                  .split(" ")
                                  .join("-")}-forward`}
                              >
                                <i className="material-icons">arrow_forward</i>
                              </button>
                              <button
                                onClick={() => this.delete(task)}
                                className="icon-only danger x-small mx-2"
                                data-testid={`${task.name
                                  .split(" ")
                                  .join("-")}-delete`}
                              >
                                <i className="material-icons">delete</i>
                              </button>
                            </div>
                          </div>
                        </li>
                      );
                    })}
                  </ul>
                </div>
              </div>
            );
          })}
        </div>
      </div>
    );
  }
}
